server:
  port: 8761
eureka:
  client:
    registerWithEureka: false   #表示是否将自己注册到Eureka Server。由于当前应用就是Eureka Server，故而设为false
    fetchRegistry: false        #表示是否从Eureka Server获取注册信息，因为这是一个单点的Eureka Server，不需要同步其他的Eureka Server节点的数据。
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/